/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar/MenuBar.vue')['default']
    PromotionBanner: typeof import('./src/components/PromotionBanner/PromotionBanner.vue')['default']
    Recommodation: typeof import('./src/components/Recommodation/Recommodation.vue')['default']
    Register: typeof import('./src/components/Register/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subscription: typeof import('./src/components/Subscription/Subscription.vue')['default']
  }
}
